package dvranjicic.cvapp

import android.support.v7.app.AppCompatActivity
import android.os.Bundle

// since there is only one activity in this app, there is no
// need to setup base activity; it is enough to have the one automatically
// generated by the Android studio

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
